name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: mvn -B package test --file pom.xml
      - name: Save test results
        if: failure()
        run: |
          mkdir -p junit
          cp target/surefire-reports/*.xml junit/
      - name: Extract test failures
        id: extract-failures
        if: failure()
        run: |
          set +e
          awk '/<testcase /{print; next} /<failure/{print; while(getline && !/<\/testcase/){print}}' junit/*.xml > failure-report.txt
          if [ -s failure-report.txt ]; then
            summary=$(cat failure-report.txt | sed 's/</&lt;/g' | sed 's/>/&gt;/g')
          else
            summary="No detailed failure information found."
          fi
          echo "::set-output name=failure-summary::$summary"
      - name: Notify Telegram on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            Build Failed ❌
            *Repository*: ${{ github.repository }}
            *Actor*: ${{ github.actor }}
            *Commit number*: ${{ github.sha }}
            *Commit is not passed test ⚠️*
            *Test Failures*:
            ```
            ${{ steps.extract-failures.outputs.failure-summary }}
            ```
      - name: Notify Telegram on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            Build Success ✅
            *Repository*: ${{ github.repository }}
            *Actor*: ${{ github.actor }}
            *Commit number*: ${{ github.sha }}
