name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: mvn -B package test --file pom.xml
      - name: Save test results
        if: failure()
        run: |
          mkdir -p junit
          cp target/surefire-reports/*.xml junit/
      - name: Annotate failure
        if: failure()
        run: |
          echo "##[group]Test Failures"
          grep -A 2 -B 2 "<failure" junit/*.xml | tee failure-report.txt
          echo "##[endgroup]"
      - name: Notify Telegram on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            Build Failed ❌
            *Repository*: ${{ github.repository }}
            *Actor*: ${{ github.actor }}
            *Commit number*: ${{ github.sha }}
            *Commit is not passed test ⚠️*
            *Test Failures*:
            ```
            ${{ steps.annotate.outputs.failure-summary }}
            ```
      - name: Notify Telegram on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            Build Success ✅
            *Repository*: ${{ github.repository }}
            *Actor*: ${{ github.actor }}
            *Commit number*: ${{ github.sha }}
