name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/

      - name: Notify Telegram on failure build
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *${{ github.actor }}* created commit.
            *Commit message: * ${{ github.event.head_commit.message }}
            *Repository *: ${{ github.repository }}
            *Commit number *: ${{ github.sha }}
            *Build Failed ❌*

      - name: Notify Telegram on success build
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *${{ github.actor }}* created commit.
            *Commit message: * ${{ github.event.head_commit.message }}
            *Repository *: ${{ github.repository }}
            *Commit number *: ${{ github.sha }}
            *Build Success ✅*
      

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: target/
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Save test results
        if: failure()
        run: |
          mkdir -p junit
          cp target/surefire-reports/*.xml junit/
      - name: Create test failure report
        if: failure()
        run: |
          set +e
          grep -E "<testcase|<failure" junit/*.xml | grep -B 1 "<failure" > failure-report.xml
      - name: Notify Telegram on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *Commit is not passed test(s) ⚠️. 
            Logs in the file:*
          document: failure-report.xml
      - name: Notify Telegram on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *Commit is passed all tests ✅*
